
version: "3"
services:
  react-client:
    image: react-client
    stdin_open: true
    ports: 
      - "5173:5173"
    networks:
      - mern-app

  java-spring:
    image: java-spring
    ports:
      - "8080:8080"
    networks:
      - mern-app
    
    depends_on:
      - react-client

networks:
  mern-app:
    driver: bridge
